export const CONFIG_SYMBOLS = Object.freeze({
  NODE_ENV: Symbol("NODE_ENV"),
  NODE_PORT: Symbol("NODE_PORT"),
  DATABASE_URI: Symbol("DATABASE_URI"),
  PUBLIC_KEY: Symbol("PUBLIC_KEY"),
  PRIVATE_KEY: Symbol("PRIVATE_KEY"),
  JWT_SIGN_OPTIONS: Symbol("JWT_SIGN_OPTIONS"),
  JWT_VERIFY_OPTIONS: Symbol("JWT_VERIFY_OPTIONS"),
});
